image: ghcr.io/uwacsds/citsbot

pushgatewayUrl: http://prometheus-pushgateway.metrics:9091

instances:
  - name: skippy
    secrets:
    - name: citsbot.config
      ref: /prod/citsbot/skippy
      properties:
      - name: token
        key: discordToken
      - name: imgurClientId
        key: imgurClientId
    botConfig:
      prefix: "!"
      guild: '951340912007577631'
      logChannel: '952079177920688129'
      modules:
        cowsay:
          lineMaxLen: 40
          cowArt: |
                   \    ^__^
                    \   (oo)\_______
                        (__)\       )\/\
                            ||----w |
                            ||     ||
        reactRoles:
          messages:
          - id: '952093570880405534'
            channel: '951464139094634557'
            reactions:
            - role: '952102842863345745'
              emoji: "📢"
          - id: '952093576098119730'
            channel: '951464139094634557'
            reactions:
            - role: '952081270177939526'
              emoji: "australiancapitalterritory"
            - role: '951437822198448208'
              emoji: "newsouthwales"
            - role: '951438933496037416'
              emoji: "northernterritory"
            - role: '951439217274286080'
              emoji: "queensland"
            - role: '951439357137518592'
              emoji: "southaustralia"
            - role: '952110091233021972'
              emoji: "tasmania"
            - role: '951729746293686272'
              emoji: "victoria"
            - role: '951437609668866069'
              emoji: "westernaustralia"
            - role: '952102132746706954'
              emoji: "newzealand"

  - name: uwacsds
    secrets:
    - name: citsbot.config
      ref: /prod/citsbot
      properties:
      - name: token
        key: discordToken
      - name: imgurClientId
        key: imgurClientId
    botConfig:
      prefix: "!"
      guild: '586127025228742656'
      logChannel: '646748400678862848'
      units:
        CITS1001:
          name: Software Engineering with Java
          role: '692565026665660456'
          channels:
            general: '586603102774493225'
            resources: '586603478529605642'
        CITS1003:
          name: Introduction to Cybersecurity
          role: '782578454809935893'
          channels:
            general: '782579436980535306'
            resources: '782579508963704832'
        CITS1401:
          name: Computational Thinking with Python
          role: '692565410037628999'
          channels:
            general: '586603452264611862'
            resources: '586603478529605642'
        CITS1402:
          name: Relational Database Management Systems
          role: '703255356221948046'
          channels:
            general: '586603246060306433'
            resources: '586603265215430779'
        STAT1400:
          name: Statistics for Science
          role: '703255357706862693'
          channels:
            general: '650536586664214530'
            resources: '650536607861964821'
        CITS2002:
          name: Systems Programming
          role: '703255358738792529'
          channels:
            general: '586599746446032929'
            resources: '586599770710343692'
        CITS2003:
          name: Open Source Tools and Scripting
          role: '782578531523362836'
          channels:
            general: '782579723016208404'
            resources: '782579758621523968'
        CITS2200:
          name: Data Structures and Algorithms
          role: '703255360231833660'
          channels:
            general: '643029400425857024'
            resources: '643029453328351242'
        CITS2211:
          name: Discrete Structures
          role: '703255361498513548'
          channels:
            general: '586600195748397127'
            resources: '586600220788260929'
        CITS2401:
          name: Computer Analysis and Visualisation
          role: '703255362924707920'
          channels:
            general: '586603720197013554'
            resources: '586603734126034945'
        CITS2402:
          name: Introduction to Data Science
          role: '703255364115890256'
          channels:
            general: '643687226403979285'
            resources: '643687245508902931'
        STAT2401:
          name: Analysis of Experiments
          role: '703255365055283241'
          channels:
            general: '643689726401970217'
            resources: '643689747818086412'
        STAT2402:
          name: Analysis of Observations
          role: '703255366367969311'
          channels:
            general: '643690709316141056'
            resources: '643690728744026113'
        CITS3001:
          name: Algorithms, Agents and Artificial Intelligence
          role: '703255367760740442'
          channels:
            general: '586600660108050511'
            resources: '586600679015972865'
        CITS3002:
          name: Computer Networks
          role: '703255368985215106'
          channels:
            general: '586576957811195904'
            resources: '586576972386402336'
        CITS3003:
          name: Graphics and Animation
          role: '703255370252157009'
          channels:
            general: '586127025228742660'
            resources: '586127432881537055'
        CITS3004:
          name: Cybersecurity
          role: '703255371925684238'
          channels:
            general: '586600932578557952'
            resources: '586600945979490304'
        CITS3006:
          name: Penetration Testing
          role: '782578792853667880'
          channels:
            general: '782579970765094943'
            resources: '782580174625439744'
        CITS3007:
          name: Secure Coding
          role: '782578894082801685'
          channels:
            general: '782580098376269854'
            resources: '782580143049801749'
        CITS3200:
          name: Professional Computing
          role: '703255373003358219'
          channels:
            general: '586602461863739411'
            resources: '587645283454681101'
        CITS3401:
          name: Data Warehousing
          role: '703255374064779265'
          channels:
            general: '643683578877837313'
            resources: '643683893878194196'
        CITS3402:
          name: High Performance Computing
          role: '703255375536848988'
          channels:
            general: '586602726515933214'
            resources: '586602764537298994'
        CITS3403:
          name: Agile Web Development
          role: '703255376962781244'
          channels:
            general: '643686741642969098'
            resources: '643687397372067840'
        ENSC3020:
          name: Digital Embedded Systems
          role: '703255377885528146'
          channels:
            general: '646359806847746069'
            resources: '646359831980146689'
        STAT3064:
          name: Statistical Learning
          role: '728988639069208597'
          channels:
            general: '728987649532231761'
            resources: '728987677898047569'
        STAT3401:
          name: Advanced Data Analysis
          role: '782579029688451073'
          channels:
            general: '782581376871825409'
            resources: '782581411026173952'
        STAT3405:
          name: Introduction to Bayesian Computing and Statistics
          role: '819563645637099573'
          channels:
            general: '819564277659861052'
            resources: '819564340860420107'
        CITS4009:
          name: Computational Data Analysis
          role: '703255355483881533'
          channels:
            general: '682802496112165114'
            resources: '682802526482858059'
        CITS4401:
          name: Software Requirements and Design
          role: '703255355483881533'
          channels:
            general: '682802607571337224'
            resources: '682802626290909271'
        CITS4402:
          name: Computer Vision
          role: '703255355483881533'
          channels:
            general: '682802646721363978'
            resources: '682802669576126537'
        CITS4403:
          name: Computational Modelling
          role: '703255355483881533'
          channels:
            general: '682802691893755904'
            resources: '682802711061725230'
        CITS4404:
          name: Artificial Intelligence and Adaptive Systems
          role: '703255355483881533'
          channels:
            general: '682802731617878078'
            resources: '682802748227452971'
        CITS4407:
          name: Open Source Tools and Scripting
          role: '703255355483881533'
          channels:
            general: '720114555560263700'
            resources: '720114608232464435'
        CITS4419:
          name: Mobile and Wireless Computing
          role: '703255355483881533'
          channels:
            general: '682802764761399305'
            resources: '682802776371494926'
        CITS5501:
          name: Software Testing and Quality Assurance
          role: '703255355483881533'
          channels:
            general: '682802789554061391'
            resources: '682802799477784641'
        CITS5503:
          name: Cloud Computing
          role: '703255355483881533'
          channels:
            general: '682802838736470016'
            resources: '682802886324912165'
        CITS5506:
          name: The Internet of Things
          role: '703255355483881533'
          channels:
            general: '682802901869133836'
            resources: '682802913688420352'
        CITS5508:
          name: Machine Learning
          role: '703255355483881533'
          channels:
            general: '690839056736583690'
            resources: '690839100143566858'
        OTHER:
          name: Other Units
          role: '704962870919692419'
          channels:
            general: '587536935593967648'
            resources: '587844098770206750'
      modules:
        cowsay:
          lineMaxLen: 40
          cowArt: |
                   \    ^__^
                    \   (oo)\_______
                        (__)\       )\/\
                            ||----w |
                            ||     ||
        welcomer:
          channel: '690144646344736853'
          newMemberDm:
            delay: 300000
            roleThreshold: 1
            instantAccountAge: 7
            message: |-
              Hey {name}, welcome to the UWA Computer and Data Science discord server! I noticed that you haven't selected any roles yet. To gain access to unit channels you need to react to the messages in #overview.

              Have a read of the rules and click the emoji reactions for the unit channels you want to see. https://i.imgur.com/W2CHMEM.gif
        announcer:
          channel: '690007478364405934'
          crontab: 0 0 * * mon
          disclaimer: "⚠️ This information is provided as a guide only and may be incomplete
            and/or inaccurate. Please consult official UWA sources. Do not rely solely on
            this list."
          image: https://i.imgur.com/2cQttpX.png
          colour: "#2598d9"
        reactRoles:
          messages:
          - id: '702884623134228601'
            channel: '702884352408682597'
            reactions:
            - role: '703255353940377701'
              emoji: "\U0001F30F"
            - role: '703255355483881533'
              emoji: pepoGrad
            - role: '703854903952539688'
              emoji: github
            - unit: OTHER
              emoji: "\U0001F4DD"
            - role: '743448303466971178'
              emoji: "\U0001F4E2"
          - id: '702884633041174870'
            channel: '702884352408682597'
            reactions:
            - unit: CITS1001
              emoji: bluej
            - unit: CITS1003
              emoji: "\U0001F512"
            - unit: CITS1401
              emoji: py
            - unit: CITS1402
              emoji: mysql
            - unit: STAT1400
              emoji: r_
          - id: '702884641731772468'
            channel: '702884352408682597'
            reactions:
            - unit: CITS2002
              emoji: c_
            - unit: CITS2003
              emoji: "\U0001F6E0️"
            - unit: CITS2200
              emoji: tree
            - unit: CITS2211
              emoji: "*️⃣"
            - unit: CITS2401
              emoji: matlab
            - unit: CITS2402
              emoji: "\U0001F468‍\U0001F52C"
            - unit: STAT2401
              emoji: "\U0001F4C8"
            - unit: STAT2402
              emoji: "\U0001F4C9"
          - id: '702884672262111313'
            channel: '702884352408682597'
            reactions:
            - unit: CITS3001
              emoji: "\U0001F9E0"
            - unit: CITS3002
              emoji: "\U0001F4E1"
            - unit: CITS3003
              emoji: gl
            - unit: CITS3004
              emoji: "\U0001F512"
            - unit: CITS3006
              emoji: "\U0001F50D"
            - unit: CITS3007
              emoji: "\U0001F510"
            - unit: CITS3200
              emoji: "\U0001F4BC"
            - unit: CITS3401
              emoji: "⛏️"
            - unit: CITS3402
              emoji: "\U0001F9BE"
            - unit: CITS3403
              emoji: html
            - unit: ENSC3020
              emoji: arduino
            - unit: STAT3064
              emoji: "\U0001F4CA"
            - unit: STAT3401
              emoji: "\U0001F4C8"
            - unit: STAT3405
              emoji: "📉"
        animeDetector:
          keywords:
          - anime
          - manga
          keywordCountThreshold: 5
        threadEnforcer:
          channels:
            - channelId: '862342865270472704'
              channelName: '#project-showcase'
              topicSingular: 'project'
              topicPlural: 'projects'
            - channelId: '910432145217028136'
              channelName: '#job-opportunities'
              topicSingular: 'job opportunity'
              topicPlural: 'job opportunities'
          ruleBreakDm: |-
            Hey {username} 👋, I deleted your message in {channelName} because all discussions about individual {topicPlural} should take place in threads 🧵.

            ℹ️ Enforcing the use of threads ensures that the {topicPlural} you and everyone else share stay as visible as possible for as long as possible. You can create a new thread by right clicking or long pressing on a message and selecting "Create Thread". Please see this article for more about Discord's threads feature: https://support.discord.com/hc/en-us/articles/4403205878423.

            💡 If you are trying to share a new {topicSingular}, please ensure you include a link to it in your message.

            🚩 If you believe this action was taken in error, please reach out to one of the server moderators.
