apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $.Chart.Name }}-{{ .Values.environment }}"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: citsbot
  template:
    metadata:
      labels:
        app: citsbot
    spec:
      containers:
        - name: citsbot
          image: "{{ $.Values.image }}:{{ $.Chart.Version }}"
          env:
            - name: ENVIRONMENT
              value: "{{ $.Values.environment }}"
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: citsbot.config.{{ $.Values.environment }}
                  key: token
            - name: CONFIG
              valueFrom:
                secretKeyRef:
                  name: citsbot.config.{{ $.Values.environment }}
                  key: config
      terminationGracePeriodSeconds: 5
