apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: citsbot
  template:
    metadata:
      labels:
        app: citsbot
    spec:
      containers:
        - name: citsbot
          image: "{{ $.Values.image }}:{{ $.Chart.Version }}"
          env:
            - name: PUSHGATEWAY_URL
              value: "{{ $.Values.pushgatewayUrl }}"
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: citsbot.config
                  key: token
            - name: IMGUR_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: citsbot.config
                  key: imgurClientId
            - name: CONFIG
              value: {{ .Values.botConfig | toJson | quote }}
      terminationGracePeriodSeconds: 5
